# Generated by Django 5.2.1 on 2026-05-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='PAID', max_length=20)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tickets.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['ticket_type', 'status'], name='bookings_bo_ticket__0c73b3_idx'), models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx')],
            },
        ),
    ]
