# Generated by Django 5.2.1 on 2026-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr_codes/'),
        ),
    ]
