# Generated by Django 5.2.1 on 2026-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pdf_ticket',
            field=models.FileField(blank=True, null=True, upload_to='booking_pdf_tickets/'),
        ),
    ]
