# Generated by Django 5.2.1 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_pdf_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
