services:
  backend:
    build: ./backend
    container_name: eventhub_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: eventhub_postgres
    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: eventhub_user
      POSTGRES_PASSWORD: eventhub_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: eventhub_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
