# Generated by Django 5.2.1 on 2026-05-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('BOOKING_CANCELED', 'Booking canceled'), ('BOOKING_USED', 'Booking used'), ('EVENT_CANCELED', 'Event canceled'), ('EVENT_REMINDER', 'Event reminder'), ('MATCH_STARTED', 'Match started'), ('MATCH_RESULT_UPDATED', 'Match result updated'), ('TOURNAMENT_FINISHED', 'Tournament finished'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__950da6_idx')],
            },
        ),
    ]
