# Generated by Django 5.2.1 on 2026-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('BOOKING_CANCELED', 'Booking canceled'), ('BOOKING_USED', 'Booking used'), ('EVENT_CANCELED', 'Event canceled'), ('EVENT_REMINDER', 'Event reminder'), ('REVIEW_CREATED', 'Review created'), ('TOURNAMENT_STARTED', 'Tournament started'), ('MATCH_STARTED', 'Match started'), ('MATCH_RESULT_UPDATED', 'Match result updated'), ('TOURNAMENT_FINISHED', 'Tournament finished'), ('SYSTEM', 'System')], db_index=True, max_length=50),
        ),
    ]
