# Generated by Django 5.2.1 on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "User registered"),
                            ("EVENT_CREATED", "Event created"),
                            ("EVENT_UPDATED", "Event updated"),
                            ("EVENT_PUBLISHED", "Event published"),
                            ("EVENT_CANCELED", "Event canceled"),
                            ("EVENT_FINISHED", "Event finished"),
                            ("TICKET_TYPE_CREATED", "Ticket type created"),
                            ("BOOKING_CREATED", "Booking created"),
                            ("BOOKING_CANCELED", "Booking canceled"),
                            ("BOOKING_EXPIRED", "Booking expired"),
                            ("BOOKING_USED", "Booking used"),
                            ("EVENT_REMINDER_SENT", "Event reminder sent"),
                            ("QR_REGENERATED", "QR regenerated"),
                            ("PDF_REGENERATED", "PDF regenerated"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_audit_user_id_a3c2bc_idx",
                    ),
                    models.Index(
                        fields=["request_id"],
                        name="audit_audit_request_06fe30_idx",
                    ),
                ],
            },
        ),
    ]
