# Generated by Django 5.2.1 on 2026-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('EVENT_CREATED', 'Event created'), ('EVENT_UPDATED', 'Event updated'), ('EVENT_PUBLISHED', 'Event published'), ('EVENT_CANCELED', 'Event canceled'), ('EVENT_FINISHED', 'Event finished'), ('TICKET_TYPE_CREATED', 'Ticket type created'), ('BOOKING_CREATED', 'Booking created'), ('BOOKING_CANCELED', 'Booking canceled'), ('BOOKING_EXPIRED', 'Booking expired'), ('BOOKING_USED', 'Booking used'), ('EVENT_REMINDER_SENT', 'Event reminder sent'), ('TOURNAMENT_CREATED', 'Tournament created'), ('TOURNAMENT_PARTICIPANT_REGISTERED', 'Tournament participant registered'), ('TOURNAMENT_REGISTRATION_OPENED', 'Tournament registration opened'), ('TOURNAMENT_STARTED', 'Tournament started'), ('TOURNAMENT_FINISHED', 'Tournament finished'), ('TOURNAMENT_CANCELED', 'Tournament canceled'), ('MATCH_RESULT_SUBMITTED', 'Match result submitted'), ('REVIEW_CREATED', 'Review created'), ('REVIEW_UPDATED', 'Review updated'), ('REVIEW_DELETED', 'Review deleted'), ('REVIEW_PUBLISHED', 'Review published'), ('REVIEW_UNPUBLISHED', 'Review unpublished'), ('QR_REGENERATED', 'QR regenerated'), ('PDF_REGENERATED', 'PDF regenerated')], db_index=True, max_length=100),
        ),
    ]
