from datetime import timedelta

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.test import TestCase
from django.utils import timezone

from apps.events.models import Event, EventCategory

User = get_user_model()


class EventModelTestMixin:
    @classmethod
    def setUpTestData(cls):
        cls.category = EventCategory.objects.create(name="Conferences")
        cls.organizer = User.objects.create_user(
            email="organizer@example.com",
            password="StrongPass123!",
            role=User.Roles.ORGANIZER,
        )
        cls.admin = User.objects.create_user(
            email="admin@example.com",
            password="StrongPass123!",
            role=User.Roles.ADMIN,
        )
        cls.regular_user = User.objects.create_user(
            email="user@example.com",
            password="StrongPass123!",
        )
        cls.superuser = User.objects.create_superuser(
            email="superuser@example.com",
            password="StrongPass123!",
        )

    def make_event(self, **overrides):
        start = timezone.now() + timedelta(days=2)
        data = {
            "title": "Django Meetup",
            "description": "Community meetup",
            "category": self.category,
            "location": "Kyiv",
            "start_datetime": start,
            "end_datetime": start + timedelta(hours=2),
            "organizer": self.organizer,
        }
        data.update(overrides)
        return Event.objects.create(**data)


class EventCategoryModelTests(TestCase):
    def test_str_returns_name(self):
        category = EventCategory.objects.create(name="Music")

        self.assertEqual(str(category), "Music")

    def test_slug_is_autogenerated(self):
        category = EventCategory.objects.create(name="Board Games")

        self.assertEqual(category.slug, "board-games")

    def test_autogenerated_slug_is_unique(self):
        first = EventCategory.objects.create(name="Music!")
        second = EventCategory.objects.create(name="Music?")

        self.assertEqual(first.slug, "music")
        self.assertEqual(second.slug, "music-1")


class EventModelTests(EventModelTestMixin, TestCase):
    def test_str_returns_title(self):
        event = self.make_event(title="Hackathon")

        self.assertEqual(str(event), "Hackathon")

    def test_slug_is_autogenerated(self):
        event = self.make_event(title="Summer Cup")

        self.assertEqual(event.slug, "summer-cup")

    def test_duplicate_title_creates_unique_slug(self):
        first = self.make_event(title="Django Meetup")
        second = self.make_event(title="Django Meetup")

        self.assertEqual(first.slug, "django-meetup")
        self.assertEqual(second.slug, "django-meetup-1")

    def test_end_datetime_must_be_after_start_datetime(self):
        start = timezone.now() + timedelta(days=1)
        event = Event(
            title="Invalid Event",
            description="Invalid",
            category=self.category,
            location="Kyiv",
            start_datetime=start,
            end_datetime=start,
            organizer=self.organizer,
        )

        with self.assertRaises(ValidationError) as context:
            event.clean()

        self.assertIn("end_datetime", context.exception.message_dict)

    def test_organizer_must_have_organizer_or_admin_role(self):
        start = timezone.now() + timedelta(days=1)
        event = Event(
            title="Invalid Organizer",
            description="Invalid",
            category=self.category,
            location="Kyiv",
            start_datetime=start,
            end_datetime=start + timedelta(hours=1),
            organizer=self.regular_user,
        )

        with self.assertRaises(ValidationError) as context:
            event.clean()

        self.assertIn("organizer", context.exception.message_dict)

    def test_admin_role_can_organize_event(self):
        event = self.make_event(organizer=self.admin)

        event.clean()

    def test_superuser_can_organize_event(self):
        event = self.make_event(organizer=self.superuser)

        event.clean()

    def test_max_participants_must_be_greater_than_zero(self):
        event = self.make_event(max_participants=0)

        with self.assertRaises(ValidationError) as context:
            event.clean()

        self.assertIn("max_participants", context.exception.message_dict)

    def test_publish_sets_status_and_publication_flag(self):
        event = self.make_event()

        event.publish()

        self.assertEqual(event.status, Event.Status.PUBLISHED)
        self.assertTrue(event.is_published)

    def test_cancel_sets_status_and_publication_flag(self):
        event = self.make_event(status=Event.Status.PUBLISHED)

        event.cancel()

        self.assertEqual(event.status, Event.Status.CANCELED)
        self.assertFalse(event.is_published)

    def test_finish_sets_status_and_publication_flag(self):
        event = self.make_event(status=Event.Status.PUBLISHED)

        event.finish()

        self.assertEqual(event.status, Event.Status.FINISHED)
        self.assertFalse(event.is_published)

    def test_is_active_for_booking_true_for_published_future_event(self):
        event = self.make_event(status=Event.Status.PUBLISHED)

        self.assertTrue(event.is_active_for_booking)

    def test_is_active_for_booking_false_for_draft_or_past_event(self):
        draft = self.make_event(title="Draft Event")
        past_start = timezone.now() - timedelta(days=2)
        past = self.make_event(
            title="Past Event",
            status=Event.Status.PUBLISHED,
            start_datetime=past_start,
            end_datetime=past_start + timedelta(hours=2),
        )

        self.assertFalse(draft.is_active_for_booking)
        self.assertFalse(past.is_active_for_booking)

    def test_is_active_for_booking_false_for_canceled_or_finished_event(self):
        canceled = self.make_event(
            title="Canceled Event",
            status=Event.Status.CANCELED,
        )
        finished = self.make_event(
            title="Finished Event",
            status=Event.Status.FINISHED,
        )

        self.assertFalse(canceled.is_active_for_booking)
        self.assertFalse(finished.is_active_for_booking)
