export const queryKeys = {
  events: (params = {}) => ["events", params],
  popularEvents: (params = {}) => ["events", "popular", params],
  event: (id) => ["event", String(id)],
  eventTickets: (eventId) => ["eventTickets", String(eventId)],
  myBookings: ["myBookings"],
  booking: (id) => ["booking", String(id)],
  bookings: (params = {}) => ["bookings", params],
  organizerEvents: (params = {}) => ["organizerEvents", params],
  eventBookings: (eventId, params = {}) => [
    "eventBookings",
    String(eventId),
    params,
  ],
  tournaments: (params = {}) => ["tournaments", params],
  organizerTournaments: (params = {}) => ["organizerTournaments", params],
  tournament: (id) => ["tournament", String(id)],
  tournamentParticipants: (id) => ["tournamentParticipants", String(id)],
  tournamentMatches: (id) => ["tournamentMatches", String(id)],
  tournamentBracket: (id) => ["tournamentBracket", String(id)],
  match: (id) => ["match", String(id)],
  notifications: (params = {}) => ["notifications", params],
  categories: ["eventCategories"],
};
